const constants = {
  ADD_BOOK: 'ADD_BOOK',
  REMOVE_BOOK: 'REMOVE_BOOK',
  TOGGLE_READ: 'TOGGLE_READ',
  SET_ORDER: 'SET_ORDER',
  SET_FILTER: 'SET_FILTER',
  SHOW_ALL: 'SHOW_ALL',
  SHOW_READ: 'SHOW_READ',
  SHOW_UNREAD: 'SHOW_UNREAD',
  FETCH_BOOKS: 'FETCH_BOOKS',
  CANCEL_FETCHING: 'CANCEL_FETCHING'
};

export default constants;
